language: cpp
dist: trusty
sudo: required
compiler:
  - g++
os:
  - linux
install:
  - sudo apt-get install build-essential
  - sudo apt-get install g++-5
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
script:
  make