language: cpp
dist: trusty
sudo: required
compiler:
  - g++

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

os:
  - linux
install:
  - sudo apt-get install build-essential
  - sudo apt-get install g++-5
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
script:
  make